Repository prgrms-web-devcourse-final-project/WEB1_2_TenPaws_BE, pull requests merged in 2024-11, with the labels that each got.

#19 [Feat] 사용자 및 관리자 엔티티 + 회원가입 로직(베타 버전)
  build.gradle
  src/main/java/com/example/tenpaws/domain/admin/entity/Admin.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserJoinDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/repositoty/UserRepository.java
  src/main/java/com/example/tenpaws/domain/user/service/UserService.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/CorsMvcConfig.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/entity/UserRole.java
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: Feature, Setting, Test

#16 [Feat] 전역 예외처리 관련 클래스 추가, 공지사항 crud 기능 추가
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementResponse.java
  src/main/java/com/example/tenpaws/domain/board/repository/AnnouncementRepository.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/global/advice/GlobalExceptionHandler.java
  src/main/java/com/example/tenpaws/global/api/ApiResponse.java
  src/main/java/com/example/tenpaws/global/config/JacksonConfig.java
  src/main/java/com/example/tenpaws/global/exception/BaseException.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Feature

#21 Feature/#8 faq CRUD 구현
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqRequest.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqResponse.java
  src/main/java/com/example/tenpaws/domain/faq/entity/Faq.java
  src/main/java/com/example/tenpaws/domain/faq/exception/FaqException.java
  src/main/java/com/example/tenpaws/domain/faq/exception/FaqTaskException.java
  src/main/java/com/example/tenpaws/domain/faq/repository/FaqRepository.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqService.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqServiceImpl.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/resources/application.properties
  src/test/java/com/example/tenpaws/domain/faq/repository/FaqRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/faq/service/FaqServiceTests.java
Labels: Feature

#25 Feat/#18 chatroom
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/test/java/com/example/tenpaws/domain/chatroom/repository/ChatRoomRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chatroom/service/ChatRoomServiceTests.java
Labels: Feature

#26 [Feat] 알림 기능 추가
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/Repository/NotificationRepository.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/domain/notification/entity/Notification.java
  src/main/java/com/example/tenpaws/domain/notification/entity/NotificationType.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationService.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Feature

#28 Feat/#18 chat message
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqServiceImpl.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/repository/ChatMessageRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceTests.java
Labels: Feature

#29 [Feat] 로그인 기능 구현 + JWT 발급 구현
  src/main/java/com/example/tenpaws/TenPawsApplication.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/repositoty/UserRepository.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/security/dto/NormalUserDetails.java
  src/main/java/com/example/tenpaws/global/security/entity/RefreshEntity.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
  src/main/java/com/example/tenpaws/global/security/repository/RefreshRepository.java
  src/main/java/com/example/tenpaws/global/security/service/NormalUserDetailsService.java
  src/main/java/com/example/tenpaws/global/security/service/RefreshTokenService.java
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: Feature, Refactor

#34 [Feat] 공지사항 작성자 기능 추가
  src/main/java/com/example/tenpaws/TenPawsApplication.java
  src/main/java/com/example/tenpaws/domain/admin/repository/AdminRepository.java
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Announcement.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/entity/Notification.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationService.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
Labels: Feature, Refactor

#35 [Feat] 사용자 로그아웃 기능 구현 + email 형식으로 로그인 기능 변경
  src/main/java/com/example/tenpaws/domain/user/dto/UserJoinDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/repositoty/UserRepository.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/security/dto/NormalUserDetails.java
  src/main/java/com/example/tenpaws/global/security/entity/RefreshEntity.java
  src/main/java/com/example/tenpaws/global/security/jwt/CustomLogoutFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
  src/main/java/com/example/tenpaws/global/security/repository/RefreshRepository.java
  src/main/java/com/example/tenpaws/global/security/service/NormalUserDetailsService.java
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: Feature, Refactor, Test

#37 [Feat] Shelter, Pet CRUD 기능 구현
  src/main/java/com/example/tenpaws/TenPawsApplication.java
  src/main/java/com/example/tenpaws/domain/facility/controller/FacilityController.java
  src/main/java/com/example/tenpaws/domain/facility/entity/Facility.java
  src/main/java/com/example/tenpaws/domain/facility/repository/FacilityRepository.java
  src/main/java/com/example/tenpaws/domain/facility/service/FacilityService.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/repository/PetRepository.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/domain/shelter/dto/ShelterRequestDTO.java
  src/main/java/com/example/tenpaws/domain/shelter/dto/ShelterResponseDTO.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
  src/main/java/com/example/tenpaws/domain/shelter/repository/ShelterRepository.java
  src/main/java/com/example/tenpaws/domain/shelter/service/ShelterService.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Feature

#39 [Refactor] 예외처리 방식 개선 : ApiResponse 제거
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/global/advice/GlobalExceptionHandler.java
  src/main/java/com/example/tenpaws/global/api/ApiResponse.java
  src/main/java/com/example/tenpaws/global/exception/ErrorResponse.java
Labels: Feature, Refactor

#41 [Refactor] Shelter, Pet 리팩토링
  build.gradle
  src/main/java/com/example/tenpaws/domain/apply/entity/Apply.java
  src/main/java/com/example/tenpaws/domain/match/entity/Match.java
  src/main/java/com/example/tenpaws/domain/match/repository/MatchRepository.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/shelter/dto/ShelterRequestDTO.java
  src/main/java/com/example/tenpaws/domain/shelter/dto/ShelterResponseDTO.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
  src/main/java/com/example/tenpaws/domain/shelter/service/ShelterService.java
Labels: Refactor

#44 Feat/#18 web socket
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageRestController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/WebSocketConfig.java
  src/main/java/com/example/tenpaws/global/interceptor/JwtChannelInterceptor.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/repository/ChatMessageRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceTests.java
Labels: Feature

#42 [Feat] reissue 로직 구현
  src/main/java/com/example/tenpaws/domain/user/controller/ReissueController.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
Labels: Feature

#46 [Feat] 매칭 시스템 개발
  build.gradle
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Image.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/recommendation/component/ChatApi.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/ApiService.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserJoinDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
Labels: Feature

#55 [Feat] Apply 기능 개발 완료
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/apply/dto/ApplyDto.java
  src/main/java/com/example/tenpaws/domain/apply/entity/Apply.java
  src/main/java/com/example/tenpaws/domain/apply/repository/ApplyRepository.java
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/facility/controller/FacilityController.java
  src/main/java/com/example/tenpaws/domain/facility/entity/Facility.java
  src/main/java/com/example/tenpaws/domain/facility/repository/FacilityRepository.java
  src/main/java/com/example/tenpaws/domain/facility/service/FacilityService.java
  src/main/java/com/example/tenpaws/domain/match/entity/Match.java
  src/main/java/com/example/tenpaws/domain/match/repository/MatchRepository.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
Labels: Feature

#60 Feat/#45 websocket notice
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/entity/ChatMessage.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesRequest.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesResponse.java
  src/main/java/com/example/tenpaws/domain/chat/unread/entity/UnReadChatMessages.java
  src/main/java/com/example/tenpaws/domain/chat/unread/repository/UnReadChatMessagesRepository.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesService.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceImpl.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqRequest.java
  src/main/java/com/example/tenpaws/domain/faq/entity/Faq.java
  src/main/java/com/example/tenpaws/domain/faq/repository/FaqRepository.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqService.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/WebSocketConfig.java
  src/main/java/com/example/tenpaws/global/websocket/HttpHandShakeInterceptor.java
  src/main/java/com/example/tenpaws/global/websocket/JwtChannelInterceptor.java
  src/main/java/com/example/tenpaws/global/websocket/WebSocketEventListener.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/repository/ChatMessageRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/unread/repository/UnReadChatMessagesRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/faq/repository/FaqRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/faq/service/FaqServiceTests.java
Labels: BugFix, Feature

#59 [Mod] Pet, Shelter, Apply Controller 코드 수정
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/apply/entity/Apply.java
  src/main/java/com/example/tenpaws/domain/apply/repository/ApplyRepository.java
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
Labels: Mod

#61 [Feat] CI / CD
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  appspec.yml
  build.gradle
  docker-compose.template.yml
  scripts/start-server.sh
  src/main/resources/.gitkeep
Labels: Feature

#64 [Feat] 사용자 CRUD 기능 추가
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateRequestDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/service/UserService.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
Labels: Feature, Refactor

#67 Feat/#45 websocket notice
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesRequest.java
  src/main/java/com/example/tenpaws/domain/chat/unread/entity/UnReadChatMessages.java
  src/main/java/com/example/tenpaws/domain/chat/unread/repository/UnReadChatMessagesRepository.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesService.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceImpl.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqResponse.java
  src/main/java/com/example/tenpaws/domain/faq/exception/FaqException.java
  src/main/java/com/example/tenpaws/domain/faq/exception/FaqTaskException.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/test/java/com/example/tenpaws/domain/chat/unread/repository/UnReadChatMessagesRepositoryTests.java
  src/test/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceTests.java
Labels: Feature
