Repository prgrms-web-devcourse-final-project/WEB1_2_TenPaws_BE, pull requests merged in 2024-12, with the labels that each got.

#66 [Feat] 관리자 생성 (임시)
  src/main/java/com/example/tenpaws/domain/admin/entity/Admin.java
  src/main/java/com/example/tenpaws/domain/admin/repository/AdminRepository.java
  src/main/java/com/example/tenpaws/global/initializer/AdminInitializer.java
Labels: Feature

#77 [Feat] SSE알림기능, 문의crud기능, 답변crud기능, PreAuthorize권한검증기능 추가
  .github/workflows/deploy.yml
  Dockerfile
  appspec.yml
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/CommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateCommentRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateInquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateCommentRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateInquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/CommentResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryDetailResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Comment.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/repository/CommentRepository.java
  src/main/java/com/example/tenpaws/domain/board/repository/InquiryRepository.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentService.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryService.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/dto/request/CreateNotificationRequest.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/domain/notification/entity/Notification.java
  src/main/java/com/example/tenpaws/domain/notification/entity/NotificationType.java
  src/main/java/com/example/tenpaws/domain/notification/factory/NotificationFactory.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationService.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/sse/SseEmitters.java
  src/main/java/com/example/tenpaws/domain/notification/sse/UserIdentifier.java
  src/main/java/com/example/tenpaws/domain/notification/template/NotificationTemplate.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/java/com/example/tenpaws/global/utils/AuthenticationUtils.java
Labels: Feature

#78 [Feat] 관리자 api 로직 구현
  src/main/java/com/example/tenpaws/domain/admin/controller/AdminController.java
  src/main/java/com/example/tenpaws/domain/admin/dto/AdminRequestDTO.java
  src/main/java/com/example/tenpaws/domain/admin/dto/AdminResponseDTO.java
  src/main/java/com/example/tenpaws/domain/admin/entity/Admin.java
  src/main/java/com/example/tenpaws/domain/admin/repository/AdminRepository.java
  src/main/java/com/example/tenpaws/domain/admin/service/AdminService.java
  src/main/java/com/example/tenpaws/global/entity/UserRole.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/java/com/example/tenpaws/global/initializer/AdminInitializer.java
  src/main/java/com/example/tenpaws/global/security/dto/AdminUserDetails.java
  src/main/java/com/example/tenpaws/global/security/service/CustomUserDetailsService.java
Labels: Feature, Mod

#82 [Mod] Pet 필요 정보 추가
  build.gradle
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/apply/repository/ApplyRepository.java
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/species/Species.java
  src/main/java/com/example/tenpaws/domain/recommendation/component/ChatApi.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/ApiService.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Mod

#84 [Feat] 공지사항 카테고리, 조회수 기능 추가
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/AnnouncementResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Announcement.java
  src/main/java/com/example/tenpaws/domain/board/entity/AnnouncementCategory.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationService.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/sse/SseEmitters.java
Labels: Feature

#88 Feat/#68 refactoring
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageRestController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesRequest.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesResponse.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesService.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceImpl.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqRequest.java
  src/main/java/com/example/tenpaws/domain/faq/dto/FaqResponse.java
  src/main/java/com/example/tenpaws/domain/faq/entity/Faq.java
  src/main/java/com/example/tenpaws/domain/notification/entity/NotificationType.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/java/com/example/tenpaws/global/security/service/CustomUserDetailsService.java
  src/main/java/com/example/tenpaws/global/websocket/WebSocketEventListener.java
  src/test/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceTests.java
Labels: Feature, Mod

#87 [Mod] AI 기능 수정
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Mod

#90 Mod/#89 faq controller api
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqService.java
  src/main/java/com/example/tenpaws/domain/faq/service/FaqServiceImpl.java
  src/test/java/com/example/tenpaws/domain/faq/service/FaqServiceTests.java
Labels: Mod

#92 [Test] 테스트 추가
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/CommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/AnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CommentRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/CreateCommentRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/InquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateAnnouncementRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/UpdateInquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryDetailResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Announcement.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentService.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryService.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/notification/Repository/NotificationRepository.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/example/tenpaws/domain/notification/entity/Notification.java
  src/main/java/com/example/tenpaws/domain/notification/factory/NotificationFactory.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationService.java
  src/main/java/com/example/tenpaws/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/sse/SseEmitters.java
  src/main/java/com/example/tenpaws/global/security/verifier/OwnershipVerifier.java
  src/main/java/com/example/tenpaws/global/utils/AuthenticationUtils.java
  src/test/java/com/example/tenpaws/domain/board/service/AnnouncementServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/board/service/CommentServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/board/service/InquiryServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/notification/service/NotificationServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: Refactor, Test

#94 Mod/#91 chat response
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatController.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/dto/ChatMessageRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomRequest.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/dto/UnReadChatMessagesRequest.java
  src/main/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceImpl.java
  src/main/java/com/example/tenpaws/global/websocket/HttpHandShakeInterceptor.java
  src/main/java/com/example/tenpaws/global/websocket/WebSocketEventListener.java
  src/test/java/com/example/tenpaws/domain/chat/chatmessage/service/ChatMessageServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/chatroom/service/ChatRoomServiceTests.java
  src/test/java/com/example/tenpaws/domain/chat/unread/service/UnReadChatMessagesServiceTests.java
  src/test/java/com/example/tenpaws/domain/notification/service/NotificationServiceIntegrationTest.java
Labels: Mod

#95 [Feat] 소셜 사용자 기능 추가 및 시큐리티 설정 변경
  src/main/java/com/example/tenpaws/domain/admin/entity/Admin.java
  src/main/java/com/example/tenpaws/domain/shelter/entity/Shelter.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserFeatureController.java
  src/main/java/com/example/tenpaws/domain/user/dto/OAuth2UserDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/OAuth2UserEntity.java
  src/main/java/com/example/tenpaws/domain/user/repositoty/OAuth2UserRepository.java
  src/main/java/com/example/tenpaws/domain/user/service/UserService.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/tenpaws/global/advice/OAuth2SuccessHandler.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/java/com/example/tenpaws/global/security/dto/OAuth2UserDetails.java
  src/main/java/com/example/tenpaws/global/security/dto/SuperAdminDetails.java
  src/main/java/com/example/tenpaws/global/security/entity/CustomOAuth2User.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/service/CustomUserDetailsService.java
  src/main/java/com/example/tenpaws/global/security/service/OAuth2UserServiceImplement.java
Labels: Feature, Refactor, Mod

#97 [Feat] 소셜 로그인 유저 이름 변경 기능 추가
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/dto/OAuth2UserDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UpdateSocialUsernameRequestDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/OAuth2UserEntity.java
  src/main/java/com/example/tenpaws/domain/user/service/UserService.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
Labels: Feature

#99 [Setting] 배포
  scripts/start-server.sh
  src/test/java/com/example/tenpaws/domain/notification/service/NotificationServiceIntegrationTest.java
Labels: Setting

#100 Mod/#96 chat social
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageRestController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserResponseForChatDTO.java
  src/main/java/com/example/tenpaws/global/security/service/CustomUserDetailsService.java
Labels: Feature, Mod

#101 [Mod] role 반환, 아이디 중복 로직 수정
  src/main/java/com/example/tenpaws/domain/user/controller/UserFeatureController.java
  src/main/java/com/example/tenpaws/domain/user/repositoty/OAuth2UserRepository.java
Labels: Refactor, Mod

#104 [DOCS] swagger-api를 위한 코드 추가
  build.gradle
  src/main/java/com/example/tenpaws/domain/admin/controller/AdminController.java
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/CommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/domain/user/controller/ReissueController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserFeatureController.java
  src/main/java/com/example/tenpaws/global/config/SwaggerConfig.java
Labels: Docs

#107 [Mod] 유저 코드 수정
  src/main/java/com/example/tenpaws/domain/user/dto/UserJoinDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateRequestDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
Labels: Mod

#105 [Feat, Refactor] 이미지 저장 기능
  src/main/java/com/example/tenpaws/domain/pet/controller/FileUploadExceptionAdvice.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Image.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/pet/species/Species.java
Labels: Feature, Refactor

#109 Feat/#108 chatroom delete alarm
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ClosedChatRoomResponse.java
Labels: Feature

#111 [Mod] fixfixfixfix
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/species/Species.java
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: BugFix

#112 [Setting] 배포
  build.gradle
  src/main/java/com/example/tenpaws/domain/admin/controller/AdminController.java
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/CommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/dto/ClosedChatRoomResponse.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/pet/controller/FileUploadExceptionAdvice.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Image.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/pet/species/Species.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/domain/user/controller/ReissueController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserFeatureController.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserJoinDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateRequestDTO.java
  src/main/java/com/example/tenpaws/domain/user/dto/UserUpdateResponseDTO.java
  src/main/java/com/example/tenpaws/domain/user/entity/User.java
  src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
  src/main/java/com/example/tenpaws/global/config/SwaggerConfig.java
  src/main/resources/.gitkeep
  src/test/java/com/example/tenpaws/domain/user/service/UserServiceImplTest.java
Labels: Setting

#114 [Mod] cors
  src/main/java/com/example/tenpaws/global/config/CorsMvcConfig.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/security/jwt/CustomLogoutFilter.java
Labels: Mod

#116 [Setting] 배포
  docker-compose.template.yml
  src/main/java/com/example/tenpaws/global/config/CorsMvcConfig.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/security/jwt/CustomLogoutFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtFilter.java
Labels: Setting

#120 mod: 채팅 및 FAQ 스웨거 수정
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageRestController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
Labels: Mod

#122 [Feat] access token
  src/main/java/com/example/tenpaws/global/security/jwt/CustomLogoutFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
Labels: Feature

#124 [Feat] 본인이 작성한 공지/문의/답변 조회 추가, 프론트 피드백 반영
  src/main/java/com/example/tenpaws/domain/board/controller/AdminCommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryDetailResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/repository/AnnouncementRepository.java
  src/main/java/com/example/tenpaws/domain/board/repository/CommentRepository.java
  src/main/java/com/example/tenpaws/domain/board/repository/InquiryRepository.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentService.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryService.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/global/security/verifier/OwnershipVerifier.java
Labels: Feature, Mod

#126 [Mod, Add] AI 기능 추가 및 수정, petResponseDTO 수정
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Mod, Add

#127 [Setting] 배포
  src/main/resources/.gitkeep
Labels: Setting

#128 [Setting] 배포
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/board/controller/AdminCommentController.java
  src/main/java/com/example/tenpaws/domain/board/controller/AnnouncementController.java
  src/main/java/com/example/tenpaws/domain/board/controller/InquiryController.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryDetailResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryListViewResponse.java
  src/main/java/com/example/tenpaws/domain/board/dto/response/InquiryResponse.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/repository/AnnouncementRepository.java
  src/main/java/com/example/tenpaws/domain/board/repository/CommentRepository.java
  src/main/java/com/example/tenpaws/domain/board/repository/InquiryRepository.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementService.java
  src/main/java/com/example/tenpaws/domain/board/service/AnnouncementServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentService.java
  src/main/java/com/example/tenpaws/domain/board/service/CommentServiceImpl.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryService.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/chat/chatmessage/controller/ChatMessageRestController.java
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/example/tenpaws/domain/chat/unread/controller/UnReadChatMessagesController.java
  src/main/java/com/example/tenpaws/domain/faq/controller/FaqController.java
  src/main/java/com/example/tenpaws/domain/notification/controller/NotificationController.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/recommendation/service/RecommendService.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
  src/main/java/com/example/tenpaws/global/security/jwt/CustomLogoutFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
  src/main/java/com/example/tenpaws/global/security/verifier/OwnershipVerifier.java
  src/main/resources/.gitkeep
Labels: Setting

#130 [Chore] pet age 타입 변경
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
Labels: Chore

#131 [Feat] 파일 업로드용 도커 볼륨 디렉토리 생성, 상황별 알림 추가
  Dockerfile
  docker-compose.template.yml
  my.cnf
  scripts/start-server.sh
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/InquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/domain/notification/factory/NotificationFactory.java
  src/main/java/com/example/tenpaws/domain/notification/template/NotificationTemplate.java
  src/main/java/com/example/tenpaws/global/security/verifier/OwnershipVerifier.java
  src/test/java/com/example/tenpaws/domain/board/service/CommentServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/board/service/InquiryServiceIntegrationTest.java
Labels: BugFix, Feature, Setting, Mod

#132 [Setting] 배포
  src/main/resources/.gitkeep
Labels: Setting

#133 [Setting] 배포
  Dockerfile
  docker-compose.template.yml
  my.cnf
  scripts/start-server.sh
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/board/dto/request/InquiryRequest.java
  src/main/java/com/example/tenpaws/domain/board/entity/Inquiry.java
  src/main/java/com/example/tenpaws/domain/board/service/InquiryServiceImpl.java
  src/main/java/com/example/tenpaws/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/example/tenpaws/domain/notification/factory/NotificationFactory.java
  src/main/java/com/example/tenpaws/domain/notification/template/NotificationTemplate.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/global/security/verifier/OwnershipVerifier.java
  src/main/resources/.gitkeep
  src/test/java/com/example/tenpaws/domain/board/service/CommentServiceIntegrationTest.java
  src/test/java/com/example/tenpaws/domain/board/service/InquiryServiceIntegrationTest.java
Labels: Setting

#137 Mod/#136 chatroom delete
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
Labels: Mod

#138 [Setting] 배포
  .github/workflows/deploy.yml
Labels: Setting

#139 [Setting] 배포
  .github/workflows/deploy.yml
  src/main/java/com/example/tenpaws/domain/chat/chatroom/controller/ChatRoomController.java
Labels: Setting

#140 [Feat] 블랙리스트 내용 개선 및 접근 경로 강화
  src/main/java/com/example/tenpaws/global/advice/OAuth2SuccessHandler.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtFilter.java
  src/main/java/com/example/tenpaws/global/security/jwt/JwtUtil.java
  src/main/java/com/example/tenpaws/global/security/jwt/LoginFilter.java
  src/main/java/com/example/tenpaws/global/security/service/JwtBlacklistService.java
Labels: Feature, Mod

#144 [Chore] pet 사진 폴더 추가
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
Labels: Chore

#145 [Setting] 배포
  .github/workflows/deploy.yml
  appspec.yml
  docker-compose.template.yml
  my.cnf
  scripts/before_install.sh
Labels: BugFix, Setting

#146 [Hotfix] 2024-12-06 이미지 로드 오류
  .github/workflows/deploy.yml
  appspec.yml
  docker-compose.template.yml
  my.cnf
  scripts/before_install.sh
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
Labels: BugFix

#150 [Chore, Mod] 사진 시큐리티 제외 설정, 권한 검증 작업 추가
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Mod, Chore

#149 [docs] 리드미 파일 업데이트
  README.md
Labels: Docs

#147 [Chore, Mod] 사진 시큐리티 제외 설정, 권한 검증 작업 추가
  src/main/java/com/example/tenpaws/domain/apply/controller/ApplyController.java
  src/main/java/com/example/tenpaws/domain/apply/service/ApplyService.java
  src/main/java/com/example/tenpaws/domain/pet/controller/PetController.java
  src/main/java/com/example/tenpaws/domain/pet/service/PetService.java
  src/main/java/com/example/tenpaws/domain/shelter/controller/ShelterController.java
  src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
  src/main/java/com/example/tenpaws/global/exception/ErrorCode.java
Labels: Mod, Chore

#152 [Docs] CI/CD
  README.md
  appspec.yml
Labels: Docs

#156 [Chore] : pet stauts 추가
  src/main/java/com/example/tenpaws/domain/pet/dto/PetResponseDTO.java
  src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
Labels: Chore

#162 [Update] 프론트엔드 코드 업데이트
  frontend/src/components/Header.tsx
  frontend/src/pages/matching/MatchingPage.tsx
  frontend/src/pages/my/MyPageShelter.tsx
Labels: Add

#163 [Chore] pet requestDTO update
  backend/src/main/java/com/example/tenpaws/domain/pet/dto/PetRequestDTO.java
Labels: Chore

#164 [Mod] nginx 서버 설정 변경
  nginx.conf
Labels: Mod

#166 [feat] 소셜 유저 삭제
  backend/src/main/java/com/example/tenpaws/domain/user/controller/UserController.java
  backend/src/main/java/com/example/tenpaws/domain/user/service/UserService.java
  backend/src/main/java/com/example/tenpaws/domain/user/service/UserServiceImpl.java
Labels: Feature

#169 chore : Update Pet.java
  backend/src/main/java/com/example/tenpaws/domain/pet/entity/Pet.java
Labels: BugFix

#172 [mod] 스웨거 관련 경로 추가 확장
  backend/src/main/java/com/example/tenpaws/global/config/SecurityConfig.java
Labels: Mod
